'use client';
import {Activity,Boxes,Command,FileCode2,FolderTree,Layers3,Network,RefreshCw,Search,Server,Terminal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {requestJSON,inputTemplate,statusCounts,type Registry,type Job,type Snapshot,type Target,type StoredObject} from './model';
import {useWorkspace} from './state';
import {Json} from './result-panel';
export function ExecutionConsole(){const {view,setView,registry,snapshot,jobs,targets,files,errors,busy,query,setQuery,notice,setNotice,capabilityId,setCapabilityId,namespace,setNamespace,input,setInput,result,setResult,selectedNode,setSelectedNode,objectName,setObjectName,content,setContent,opened,sector,setSector,operation,setOperation,parameters,setParameters,refresh,capability,counts,filteredFiles,filteredCapabilities,act,execute,openFile}=useWorkspace();return <div className="kw-console-grid"><section className="kw-panel"><h2><Command size={19}/> Runtime capabilities</h2><p className="kw-help">Select a registered handler and provide its input contract.</p><div className="kw-capabilities">{filteredCapabilities.map(c=><Button variant="ghost" key={c.id} className={'kw-capability '+(c.id===capabilityId?'kw-selected':'')} onClick={()=>{setCapabilityId(c.id);setInput(inputTemplate(c))}}><span>{c.id.replace(/^(agent|skill):\/\/engineering\//,'')}</span><small>{c.cloud_state}</small></Button>)}</div></section><section className="kw-panel"><h2><Terminal size={19}/> Execution workspace</h2>{capability?<><p className="kw-code-label">{capability.id}</p><p className="kw-help">{capability.input_constraints.effect||capability.reason}</p><label>Namespace<Input value={namespace} onChange={e=>setNamespace(e.target.value)}/></label><label className="kw-label">Input JSON<Textarea aria-label="Input JSON" className="kw-editor" value={input} onChange={e=>setInput(e.target.value)}/></label><Button disabled={busy} onClick={()=>void act(execute)}>Execute handler</Button><details className="kw-contract"><summary>Input contract and binding</summary><Json value={capability}/></details></>:<p className="kw-empty">Select a capability to open its execution workspace.</p>}<Tabs defaultValue="result"><TabsList className="kw-tabs"><TabsTrigger value="result">Result</TabsTrigger><TabsTrigger value="history">Execution history</TabsTrigger></TabsList><TabsContent value="result">{result?<Json value={result}/>:<p className="kw-empty">Execution results appear here.</p>}</TabsContent><TabsContent value="history">{registry.records.map(row=><Button variant="ghost" className="kw-history" key={row.id} onClick={()=>void act(async()=>setResult(await requestJSON('/api/workspace?receipt='+encodeURIComponent(row.id))))}><span>{row.id}</span><small>{row.state}</small></Button>)}</TabsContent></Tabs></section></div>;}
