'use client';
import {Activity,Boxes,Command,FileCode2,FolderTree,Layers3,Network,RefreshCw,Search,Server,Terminal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {requestJSON,inputTemplate,statusCounts,type Registry,type Job,type Snapshot,type Target,type StoredObject} from './model';
import {useWorkspace} from './state';
import {Json} from './result-panel';
export function SectorDelivery(){const {view,setView,registry,snapshot,jobs,targets,files,errors,busy,query,setQuery,notice,setNotice,capabilityId,setCapabilityId,namespace,setNamespace,input,setInput,result,setResult,selectedNode,setSelectedNode,objectName,setObjectName,content,setContent,opened,sector,setSector,operation,setOperation,parameters,setParameters,refresh,capability,counts,filteredFiles,filteredCapabilities,act,execute,openFile}=useWorkspace();return <><section className="kw-panel"><h2><Layers3 size={19}/> Submit sector work</h2><div className="kw-submit-grid"><label>Sector<Select value={sector} onValueChange={setSector}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['core','cli','ide','ci','all'].map(s=><SelectItem key={s} value={s}>{s.toUpperCase()}</SelectItem>)}</SelectContent></Select></label><label>Operation<Select value={operation} onValueChange={setOperation}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{['qualify','architecture','cli','file-list','file-read','file-save'].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></label></div><label className="kw-label">Worker parameters JSON<Textarea aria-label="Worker parameters JSON" className="kw-editor kw-short-editor" value={parameters} onChange={e=>setParameters(e.target.value)}/></label><Button disabled={busy} onClick={()=>void act(async()=>{const queued=await requestJSON<{job:{id:string}}>('/api/braink-ci',{op:'submit',id:crypto.randomUUID().replaceAll('-',''),sector,operation,parameters:JSON.parse(parameters)});setNotice('Queued '+queued.job.id+'. Worker results will appear below.')})}>Submit to sector worker</Button></section><section className="kw-panel"><h2>Builds and execution artifacts</h2><Table><TableHeader><TableRow><TableHead>Sector / operation</TableHead><TableHead>Status</TableHead><TableHead>Updated</TableHead><TableHead>Record</TableHead></TableRow></TableHeader><TableBody>{jobs.map(job=><TableRow key={job.id}><TableCell>{job.sector}<small className="kw-table-small">{job.detail.request?.operation}</small></TableCell><TableCell>{job.status}</TableCell><TableCell>{new Date(job.updated).toLocaleString()}</TableCell><TableCell><details><summary>Inspect</summary><Json value={job}/>{job.detail.artifacts?.map(artifact=><a className="kw-artifact" key={artifact.path} href={'/api/braink-ci?job='+encodeURIComponent(job.id)+'&artifact='+encodeURIComponent(artifact.path)}>{artifact.path}</a>)}</details></TableCell></TableRow>)}</TableBody></Table>{!jobs.length&&<p className="kw-empty">No jobs have been submitted.</p>}</section></>;}
