'use client';
import {Activity,Boxes,Command,FileCode2,FolderTree,Layers3,Network,RefreshCw,Search,Server,Terminal} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Tabs,TabsContent,TabsList,TabsTrigger} from '@/components/ui/tabs';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {requestJSON,inputTemplate,statusCounts,type Registry,type Job,type Snapshot,type Target,type StoredObject} from './model';
import {useWorkspace} from './state';
import {Json} from './result-panel';
export function Overview(){const {view,setView,registry,snapshot,jobs,targets,files,errors,busy,query,setQuery,notice,setNotice,capabilityId,setCapabilityId,namespace,setNamespace,input,setInput,result,setResult,selectedNode,setSelectedNode,objectName,setObjectName,content,setContent,opened,sector,setSector,operation,setOperation,parameters,setParameters,refresh,capability,counts,filteredFiles,filteredCapabilities,act,execute,openFile}=useWorkspace();return <><div className="kw-metrics">{[['Callable handlers',registry.capabilities.filter(c=>c.cloud_state==='BOUND').length],['Persisted namespaces',registry.namespaces.length],['Sector jobs',jobs.length],['Stored files',files.length]].map(([label,value])=><article className="kw-metric" key={label}><p>{label}</p><strong>{value}</strong></article>)}</div><div className="kw-grid"><section className="kw-panel"><h2><Server size={19}/> Runtime domains</h2>{snapshot?.domains.map(domain=><div className="kw-row" key={domain.id}><div><strong>{domain.name}</strong><small>{domain.kind}</small></div><span className="kw-tag">{domain.state}</span></div>)}{!snapshot&&<p className="kw-empty">No runtime observation received.</p>}</section><section className="kw-panel"><h2><Layers3 size={19}/> Delivery activity</h2><div className="kw-distribution">{Object.entries(counts).map(([state,count])=><div key={state}><span>{state}</span><strong>{count}</strong><div className="kw-bar" style={{width:Math.max(2,count/Math.max(jobs.length,1)*100)+'%'}}/></div>)}</div>{jobs.slice(0,4).map(job=><Button variant="ghost" className="kw-job-link" key={job.id} onClick={()=>setView('delivery')}><span>{job.sector} / {job.detail.request?.operation||'build'}</span><span>{job.status}</span></Button>)}{!jobs.length&&<p className="kw-empty">No sector jobs recorded.</p>}</section></div><section className="kw-panel"><h2><Boxes size={19}/> Architecture automation</h2><div className="kw-targets">{targets.map(target=><details key={target.id}><summary><span>{target.title}</span><small>{target.evidence?'Evidence recorded':'No observation'}</small></summary><Json value={target.evidence}/></details>)}</div></section></>;}
